project:
  type: website

website:
  title: "Max Warriner"
  sidebar:
    style: "docked"
    collapse-level: 1
    search: false
    contents:
      - href: index.qmd
        text: "About Me"
        icon: person
      # Resume
      - href: resume.qmd
        text: "Resume"
        icon: filetype-pdf
      # Coursework
      - section: "Coursework"
        icon: book
        contents:
        # Data Analysis I
          - section: "Data Analysis I"
            contents:
              - href: Data Analysis I/overview.qmd
                text: "Overview"
              - href: Data Analysis I/HW1/HW1.qmd
                text: "Homework 1"
              - href: Data Analysis I/HW2/HW2.qmd
                text: "Homework 2"
              - href: Data Analysis I/HW3/HW3.qmd
                text: "Homework 3"
              - href: Data Analysis I/HW4/HW4.qmd
                text: "Homework 4"
              - href: Data Analysis I/HW5/HW5.qmd
                text: "Homework 5"
              - href: Data Analysis I/HW6/HW6.qmd
                text: "Homework 6"
              - href: Data Analysis I/HW7/HW7.qmd
                text: "Homework 7"
        # Data Analysis II
          - section: "Data Analysis II"
            contents:
      # Research
      - section: "Research"
        icon: bar-chart
        contents:
        - href: dog_research.qmd
          text: "Dog Mitochondria (Published)"
        - href: Taye_Lab/quarto.qmd
          text: "Socioeconomic Factor Effects on Gut Microbiome Composition of Ethiopian Schoolchildren"
        - href: MATH481_Max_Alta/quarto.qmd
          text: "Dietary Factor Machine Learning on Gut Microbiome/Metabolome Composition of Ethiopian Schoolchildren"
      # Internships
      - section: "Internships"
        icon: briefcase
        contents:
        - href: ionia.qmd
          text: "Public Health Report on Ionia County, MI"
        - href: dsc.qmd
          text: "Colgate Data Science Collaboratory"
        - href: voting.qmd
          text: "County Voting Data for Michigan"                    
      # AI Use
      - href: ai.qmd
        text: "Statement on AI Use"
        icon: anthropic


  page-footer:
    left: "© 2026 Colgate University Student Portfolio"
    right: "[GitHub Source](https://github.com/MaxWarriner)"


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto

