{
  "hash": "d7099bbf6b432bd86bc71bea6d705dd1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Mixed Effects Regression Article           # Title of the document\n\n# Bibliography Details\nbibliography: bib.bib  # Name of bib file in the same folder \nbibliographystyle: apa                   # Bibliography style\n\nexecute:\n  warning: false\n  message: false\n\nformat:\n  html: \n    number-sections: TRUE\n    code-fold: TRUE\n    code-line-numbers: TRUE\n    cap-location: top \n  pdf:\n    documentclass: article\n    number-sections: TRUE\n    reference-section-title: \"References\" \n    code-fold: TRUE\n    code-line-numbers: TRUE\n    cap-location: top \n    include-in-header:\n      - text: |\n          \\usepackage{amsmath}\n          \\usepackage[dvipsnames]{xcolor}\n          \\usepackage[shortlabels]{enumitem}\n          \\usepackage{parskip}\n          \\usepackage{hyperref}\n          \\usepackage{geometry}\n          \\usepackage{float}\n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\nformat-links: [pdf]\n---\n\n\n \\normalsize\n\n\n::: {.cell}\n\n:::\n\n\n \\normalsize\n\n# Background\n\n## Understanding the Technique\n\nLinear mixed effects regression builds upon standard linear regression that assumes each observation/data point is independent. When we measure the same subject under different conditions, obviously those measurements are not independent. However, this can be addressed with a few changes. Instead of ignoring that we've repeated measurements on the same subject, they are built into the model. If we simply treated subject as a fixed effect, when the levels of the fixed effect are expanded into binary coefficients (subject = 1, subject = 2, ...), that would add $n-1$ new variables, rapidly inflating dimensionality. To prevent that, each subject is given its own regression model with a unique intercept: \n\n\\begin{align*}\n   Y_{ij} &= (\\underbrace{\\gamma_{0i}}_{\\textrm{rand. int.}} +  \\beta_0) + \\beta_1 x_{1ij} + \\beta_2 x_{2ij} + \\cdots + \\beta_{p-1} x_{(p-1)ij} + \\epsilon_{ij},\n\\end{align*}\nwhere:\n\n * $i=1, 2, ..., n$ is the index for the subjects \n * $j=1, 2, ..., n_i$ is the index for the observation on subject $i$. \n\n## Finding a Study\n\n```{=html}\n<iframe width=\"100%\" height=\"200px\" src=\"https://pubmed.ncbi.nlm.nih.gov/42686906/\" title=\"Journal Article\"></iframe>\n```\n\nBecause the journal Nature requires data availability in recently published papers, that allows for a large variety in available data sets for use in this portfolio. Especially appreciated is authors who provide their data directly instead of requiring the corresponding author to reply to an email... but anyways. \n\nSearching through recently published articles with search terms like, \"mixed effects\", \"repeated measures\", \"regression\", etc., I found a recently published article titled \"Late-life semaglutide treatment slows ageing and extends lifespan in female mice.\" After looking through the methods and seeing multiple mentions of the use of linear mixed-effects models, I felt this paper would work for an attempt at reproduction [@Feng2026].\n\n## Goal of the Study\n\nIncreasing amounts of research has been published on medications known as 'GLP-1' drugs, which stands for 'glucagon-like-peptide-1.'\n\n\n \\normalsize\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Trend of Published Research on 'GLP-1'](WriteUp_files/figure-pdf/fig-glp_time-1.pdf){#fig-glp_time}\n:::\n:::\n\n\n \\normalsize\n\n\n Put simply, these drugs mimic the afforementioned GLP-1 hormone produced in the human body that serves to regulate appetite and lower the risk of over-eating. Initially created as a drug for those with Type II diabetes, the broader effects on reducing obesity have made them one of the most important drugs developed in decades. The most well known of these drugs is known commercially as 'Ozempic' and scientifically as semaglutide [@williamsGLP1].\n\n ![Source - Ozempic.com](ozempic.png){width=40%}\n\nThe journal article by Feng et al. looks to investigate potential benefits of semaglutide beyond obesity, such as alleviating the effects of aging. It's been shown that a reduction in excess calories extends lifespan in humans and other animals. Do GLP-1 drugs help with aging in the same way as a diet with restricted calories, or do they work in different ways? This article looks at measures of aging among mice in three groups: \n\n|Control | Calorie Restricted Diet | Semaglutide Treatment|\n|:--     |:--:         |:--:|  \n|n = 10    | n = 10   | n = 10|\n\n\n Calorie Restricted mice were given controlled portions of food, while the control and semaglutide mice had unlimited food. \n\n\n ![Source: Charles River](mouse.png){width=40%}\n\n\n While the study uses several different measures of aging, I'm going to focus on the performance of the mice in the Barnes Maze. The Barnes Maze is a test used on mice and rats that tests their ability to recognize previous visual cues [@barnes]. When tested, they see how long the mouse stays in the quadrant it's been conditioned to remember as the exit (the longer time the better the memory). As the measure used is time (continuous), there should be no problems modelling it with a linear mixed-effects model. \n\n![Source: ScienceDirect](maze.jpg){width=40%}\n\n## Goal of Statistical Analysis\n\nThe goal of their analysis with the Barnes Maze test is to see if the slopes of the treatments are different with respect to time. \n\nThe basic model of their regression is as follows: \n\n\\begin{align*}\n   t_{ij} &= (\\underbrace{\\gamma_{0i}}_{\\textrm{random intercept}} + \\beta_0) + \\beta_1(x_{1ij})I(x_{2ij} = \\text{\"Calorie Restricted Diet\"}) + \\\\ \n   & \\beta_2(x_{1ij})I(x_{3ij} = \\text{\"Semaglutide\"}) + \\epsilon_{ij}\n\\end{align*}\nwhere:\n\n- $t$ is the time each mouse spends in the correct quadrant\n- $i=1, 2, ..., n$ is the index for each mouse\n- $j=1, 2, ..., n_i$ is the index for the observation on mouse $i$. \n- $\\gamma$ is the random intercept for the time each mouse takes to complete the maze\n- $\\beta_0$ is the intercept which includes the slope of time for mice in the \"Control\" treatment\n- $\\beta_1$ is the slope of time for mice in the \"Calorie Restricted\" treatment\n- $\\beta_2$ is the slope of time for mice in the \"Semaglutide\" treatment\n- $\\epsilon$ is the conditional residual\n\n# Reproduction of the Study\n## Data Cleaning\n\nHere's the cleaning I did to the original data file available for download in the paper [@tidyverse]: \n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- read_csv('mice.csv')\ndat <- dat[1:3,]\n\ndat <- data.frame(t(dat))\ncolnames(dat) <- dat[1,]\ndat <- dat[-1,]\ndat$subject <- 1:30\ndat$treatment <- rep(c(\"Control\", \"Sema\", \"CR\"), each = 10)\nrownames(dat) <- NULL\ndat <- dat |>\n  pivot_longer(cols = c(\"0 month\", \"2 month\", \"4 month\"), \n               names_to = \"months\", \n               values_to = \"time\")\ndat$months <- rep(c(0,2,4), 30)\n\nwrite_csv(dat, 'mice.csv')\n```\n:::\n\n\n \\normalsize\n\n## Data Summary\n\nFirst, let's look at the raw data [@ggplot2], [@random], [@ggthemes]:\n\n\n \\normalsize\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Maze Time Across Treatments and Mouse](WriteUp_files/figure-pdf/fig-raw-1.pdf){#fig-raw}\n:::\n:::\n\n\n \\normalsize\n\nA little messy, but there's a clear decline in time in the control group that's not as present in the calorie restricted or semaglutide groups. \n\nWhat if we summarize this and take the individual out of it?\n\n\n \\normalsize\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Maze Time Across Treatments](WriteUp_files/figure-pdf/fig-summary-1.pdf){#fig-summary}\n:::\n:::\n\n\n \\normalsize\n\n\nIn this view, the differences in time across diet appear to widen as time goes on. \n\n## Model Assumptions\n\nLet's check if our model fits the assumptions of linear mixed-effects regression [@lmerTest], [@patchwork]. \n\n### Normality of Conditional Residuals\n\n\n \\normalsize\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Model Conditional Residuals](WriteUp_files/figure-pdf/fig-conditional_residuals-1.pdf){#fig-conditional_residuals}\n:::\n:::\n\n\n \\normalsize\n\nWhen looking for normality, we check that a histogram is centered around 0 and appears roughly gaussian shaped, and that our points fit relatively closely to a qqplot of the normal distribution. In the case of our model, our conditional residuals are centered around 0 and do appear to be roughly gaussian shaped, with the distribution weighted slightly towards negative residuals. The qq-plot shows a close fit to a theoretical distribution. And while not necessarily the best test of approximate normality, a Shapiro-Wilk test for normality shows no statistically discernible deviation from normality ($p = 0.41$)\n\n### Multivariate Normality of Marginal Residuals\n\n\n \\normalsize\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Model Marginal Residuals](WriteUp_files/figure-pdf/fig-marginal_residuals-1.pdf){#fig-marginal_residuals}\n:::\n:::\n\n\n \\normalsize\n\nA qq-plot of our Mahalanobis distances show that the marginal residuals fit well with a multivariate normal distribution. \n\n### Normality of Random Intercepts\n\nLikely due to small sample size (3 observations per mouse), the linear mixed model is singular, meaning that it's not able to detect variance due to random intercepts:\n\n\\begin{align}\n\\gamma_i = 0 \\, \\forall \\, i \\in \\{1, 2, ...\\, , n = 30\\}\n\\end{align}\n\n## Model Fit\n\n\n \\normalsize\n\n\n::: {.cell}\n\n:::\n\n\n \\normalsize\n\nTesting the $R^2$ for the model:\n\n- Conditional $R^2 =$ NA\n- Marginal $R^2 = 0.379$\n\nBecause our model was singular and wasn't able to detect any random effects of the individual subjects, our conditional $R^2$ was not able to be calculated. This means there is also no intraclass correlation coefficient.\n\nTesting the model performance [@performance]:\n\n\n\n \\normalsize\n\n\n::: {#tbl-mod_performance .cell tbl-cap='Model Performance Metrics'}\n\n:::\n\n\n \\normalsize\n\n\n## Model Inference\n\nWhile the data does violate the assumptions of a linear mixed-effect model because of the singularity and inability to detect variance in the random effects, we'll continue with the analysis as attempted in the article. \n\nA simple summary of our model gives us: \n\n\n \\normalsize\n\n\n::: {#tbl-mod_summary .cell}\n::: {.cell-output-display}\n\n\nTable: Model Summary\n\n|                                        |Estimate |    SE| df |      t|      p|\n|:---------------------------------------|:--------|-----:|:--:|------:|------:|\n|Intercept                               |36.394   | 3.659| 84 |  9.947| <0.001|\n|Months                                  |-3.198   | 1.417| 84 | -2.257|  0.027|\n|Treatment = Calorie Restricted          |-1.991   | 5.175| 84 | -0.385|  0.701|\n|Treatment = Semaglutide                 |0.423    | 5.175| 84 |  0.082|  0.935|\n|Months : Treatment = Calorie Restricted |3.650    | 2.004| 84 |  1.821|  0.072|\n|Months : Treatment = Semaglutide        |8.902    | 2.004| 84 |  4.442| <0.001|\n\n\n:::\n:::\n\n\n \\normalsize\n\n\nOur model summary shows us that there's evidence for a statistically discernable effect of months on time spent in the correct quadrant for mice ($t(84) = 9.947$, $p = 0.027$). Our model predicts that for every treatment, for every additional month, a mouse spends 3.2 fewer seconds in the correct quadrant. \n\nAdditionally, the interaction between months and the calorie restricted treatment shows a marginal effect of months on time spent in the correct quadrant for mice ($t(84) = 1.821, p = 0.072$). Our model predicts that for the calorie restricted group, for each additional month, a mouse spends 3.650 more seconds in the correct quadrant. \n\nLastly, the interaction between months and the semaglutide treatment shows a statistically discernible effect of months on time spent in the correct quadrant for mice ($t(84) = 4.442, p < 0.001$). Our model predicts that for the semaglutide group, for each additional month, a mouse spends 8.902 more seconds in the correct quadrant. \n\nTesting the effect sizes of our fixed effects [@r2glmm]: \n\n\n \\normalsize\n\n\n::: {#tbl-model_eff .cell}\n::: {.cell-output-display}\n\n\nTable: Model Effect Sizes\n\n|       Effect       | R-Squared| Upper CI| Lower CI|\n|:------------------:|---------:|--------:|--------:|\n|       Model        |     0.379|    0.258|    0.533|\n| Months : Treatment |     0.183|    0.072|    0.340|\n|       Months       |     0.054|    0.002|    0.174|\n|     Treatment      |     0.003|    0.001|    0.088|\n\n\n:::\n:::\n\n\n \\normalsize\n\nOur model explains 37.9\\% of the variation in time spent in the correct quadrant by mice (95\\% CI: [0.258, 0.533]). By effect:\n\n- The interaction between months and treatment type explains 18.3\\% of the variation in time spent in the correct quadrant by mice (95\\% CI: [0.072, 0.340]).\n- The effect of months explains 5.4\\% of the variation in time spent in the correct quadrant by mice (95\\% CI: [0.002, 0.174]).\n- The effect of treatment type explains 0.3\\% of the variation in time spent in the correct quadrant by mice (95\\% CI: [0.001, 0.088]).\n\n## Model Interactions\n\nNow we attempt to untangle the interaction that is at the heart of this study: the effect of months across different treatment groups. \n\nTo model the slope of months across different treatment groups, we use Estimated Marginal Trends [@emmeans]:\n\n\n \\normalsize\n\n\n::: {#tbl-model_emt .cell}\n::: {.cell-output-display}\n\n\nTable: Model Estimated Marginal Trends\n\n|Treatment          | Months Trend |    SE| df|      t|      p| adjusted-p| Lower CI | Upper CI |\n|:------------------|:------------:|-----:|--:|------:|------:|----------:|:--------:|:--------:|\n|Control            |    -3.198    | 1.417| 57| -2.257|  0.028|      0.042|  -6.036  |  -0.361  |\n|Calorie Restricted |    0.452     | 1.417| 57|  0.319|  0.751|      0.751|  -2.386  |  3.289   |\n|Semaglutide        |    5.703     | 1.417| 57|  4.025| <0.001|      0.001|  2.866   |  8.541   |\n\n\n:::\n:::\n\n\n \\normalsize\n\nUsing the estimated marginal trends, our model predicts:\n\n- For the control group, each additional month *decreases* the amount of time the mouse spends in the correct quadrant by 3.198 seconds (95\\% CI: [-6.036, -0.361]). This trend is statistically discernible ($t(57) = -2.257, p = 0.028$, adjusted-$p = 0.042$).\n- For the calorie restricted group, each additional month *increases* the amount of time the mouse spends in the correct quadrant by 0.452 seconds (95\\% CI: [-2.386, 3.298]). This trend did not reach traditional levels of statistical significance.\n- For the semaglutide treatment group, each additional month *increases* the amount of time the mouse spends in the correct quadrant by 5.703 seconds (95\\% CI: [2.866, 8.541]). This trend is statistically discernible ($t(57) = 4.025, p< 0.001$, adjusted-$p = 0.001$).\n\nVisualizing those trends: \n\n\n \\normalsize\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Model Estimated Marginal Trends](WriteUp_files/figure-pdf/fig-marginal_trends-1.pdf){#fig-marginal_trends}\n:::\n:::\n\n\n \\normalsize\n\n\nTesting the differences in those trends: \n\n\n \\normalsize\n\n\n::: {#tbl-model_emt_cont .cell}\n::: {.cell-output-display}\n\n\nTable: Model Estimated Marginal Trends Contrasts\n\n|             Contrast             | Estimate |    SE| df |      t|      p| adjusted-p | Lower CI | Higher CI |\n|:--------------------------------:|:--------:|-----:|:--:|------:|------:|:----------:|:--------:|:---------:|\n|   Control - Calorie Restricted   |  -3.650  | 2.004| 57 | -1.821|  0.172|   0.172    |  -8.473  |   1.173   |\n|      Control - Semaglutide       |  -8.902  | 2.004| 57 | -4.442| <0.001|   <0.001   | -13.724  |  -4.079   |\n| Calorie Restricted - Semaglutide |  -5.252  | 2.004| 57 | -2.620|   0.03|   0.045    | -10.074  |  -0.429   |\n\n\n:::\n:::\n\n\n \\normalsize\n\n\nA pairwise comparison shows us that there is statistically significant evidence that the slope of month for the semaglutide treatment is greater than the control ($t(57) = 4.442, p<0.001$, adjusted-$p<0.001$); The estimated difference is 8.902 (95\\% CI: [4.079, 13.724]). There is also statistically significant evidence that the slope of month for the semaglitude treatment is greater than the calorie restricted treatment ($t(57) = 2.620, p = 0.03$, adjusted-$p = 0.045$). The estimated difference is 5.252 (95\\% CI: [0.429, 10.074]). \n\n\n## Conclusions\n\n### A Note on Model Assumptions and Truthfulness\n\n ![Source: McCartney Times](beatles.png){width=80%}\n\n\nTo find a paper, especially with as many analyses contained in like this one, that formally checks the assumptions of the statistical model chosen is exceptionally rare. It's also true that there's a fine line between advocacy and pedanticism when doing statistics. You can often feel like you're yelling into a void as someone specializing in the statistics side of science. At a certain point we must recognize that the $p$-value is here to stay, if something can be a $t$-test, it will, and assumptions are for statisticians and no one else. That doesn't mean that they don't matter though. Maybe if people checked their assumptions more, reproducability would be higher in certain fields. I have no idea whether the authors of this article checked the assumptions of this linear mixed-model. In the reporting summary, the authors confirm that any assumptions are present in the main paper, the supplementary figures, or figure legends. It's not hard to check that this isn't true. The authors didn't include any of the assumptions for the $t$-test either until reviewer #2 pointed it out. Once again, the only statistics people care about is the $t$-test.\n\nIt's always jarring to me how many different tests and analyses researchers cram into their papers. I've analyzed one tiny part of the paper I'm using for this article. All of this analysis I've produced is stuffed into one square of a 9x9 grid of 1 out of 9 total figures. It's like I've just analyzed one verse of one song of the Beatles White Album. Maybe this is a bad metaphor because the White Album is fantastic, but how many White Album journal articles could've been Abbey Road articles if more care was given to each test, each model, and each assumption?\n\nAlthough I think the evidence for their hypothesis is strong, I'd feel more strongly about it if each mouse had 1-2 more observations, making it more likely that the mixed-effects model wasn't singular. That fact at least requires the results are paired with an unknowably large grain of salt. \n\n\n### Summary of the Results\n\nEvidence for an interaction between months (a.k.a time) and treatment type is strong. That interaction explains a large proportion of the variance in time in the correct quadrant for the mice, much larger than either fixed effect alone ([@tbl-model_eff]).\n\nThe difference in slopes for months across treatment time is very visually apparent ([@fig-marginal_trends]). The difference is strongest between the semaglutide treatment and the control group ([@tbl-model_emt_cont]). \n\nHowever, the main goal of the research is to see if the semaglutide group ages differently than the calorie restricted group, and if that could mean something for effects of people on GLP-1 drugs as they age. In the comparison of those two groups, I'd say the difference is promising, but not strong enough to definitely conclude anything by itself for two reasons: \n\n1. The mixed effects model didn't pass all of the assumptions, possibly because of the small number of observations per mouse.\n2. Depending on who you ask, $0.01<p<0.05$ could mean statistically significant, marginally significant, or not significant at all. \n\nWith increased sample size and better behaved model however, I think it's plausible the results continue to point in the direction that was hypothesized. \n\n# Agreements \\& Disagreements With the Article\n\n## Methods\n\nAs far as I can tell, this is the entirety of the author's discussion on this analysis in the manuscript: \"Other longitudinal continuous data were analysed using linear mixed-effects models to assess ageing trajectories. Slopes for each group were determined and pairwise comparisons of slopes were performed with Tukey adjustment.\"\n\nI've never personally heard of using Tukey's adjustment for anything but ANOVA, but Claude AI tells me it's an option for the pairs() function in *R*. \n\nDoing that adjustment instead of the Benjamini-Hochberg I'm accustomed to gives these differences:\n\n\n \\normalsize\n\n\n::: {#tbl-p_adjust_comparison .cell}\n::: {.cell-output-display}\n\n\nTable: Comparison of Adjustment Methods\n\n|            Comparison            |  Raw   |   BH   | Tukey  |\n|:--------------------------------:|:------:|:------:|:------:|\n|   Control - Calorie Restricted   | 0.172  | 0.172  | 0.172  |\n|      Control - Semaglutide       | <0.001 | <0.001 | <0.001 |\n| Calorie Restricted - Semaglutide |  0.03  | 0.045  |  0.03  |\n\n\n:::\n:::\n\n\n \\normalsize\n\nThis doesn't change the adjusted $p$-values much. Tukey's adjustment is slightly less harsh on the third comparison than the Benjamini-Hochberg method but that's all. \n\n## Results\n\nThe analysis reproduced corresponds to Fig. 5e in the article. Shown is the discussion in the results section and the corresponding figure: \n\n> \"Notably, semaglutide treatment led to improvements above the baseline, as well as to more favourable trajectories in contrast to calorie restriction, in open-field centre time (Fig. 5b), Barnes maze performance (Fig. 5e) and glucose tolerance (Fig. 5i). These findings indicate that GLP-1R activation late in life recapitulates many functional benefits of calorie restriction by attenuating age-associated decline, while conferring additional benefits in exploratory drive, spatial memory and glucose control, suggesting effects beyond reduced calorie intake alone.\"\"\n\n\n ![Journal Figure](paper.png){width=100%, #fig-journal_fig}\n\nCompared to my analysis of the estimated marginal trends of months ([@tbl-model_emt]), the results in the paper are exactly the same. The same is true of the contrasts between the trends across treatment groups ([@tbl-model_emt_cont]), except for my $p$-value adjustments are slightly more harsh than there's.\n\nAssuming that the researchers are using the standard cutoff ($p<0.05$), it makes sense why they use this finding, along with the rest, as evidence for positive effects on aging for semaglutide treatments in mice. However, my point about $p = 0.04$ being on the borderline also applies to their Figures 5b, 5d, and 5i, all which have $0.01<p<0.05$. While all fit within the traditional convention for statistical significance, it isn't ideal when that continually pops up across a study. I understand that sample size is often limited in animal studies for ethics reasons, but a linear mixed-effects model partially solves this issue by allowing repeated measures on the same mouse, which I still believe would've really helped this study. For where this analysis sits currently, the consistent direction in which the analyses point certainly make it promising for further studies on GLP-1 drugs and their effects on aging. \n\n\n# Acknowledgement\n\nI give my appreciation to the authors of this study: Yufan Feng, Marine Barthez, Yifei Wang, Yibing Chen, Huixian Qiu, Chih-Ling Wang, Kartoosh Heydari, Melaine Delcroix, Lene Juel Rasmussen, Vilhelm A. Bohr \\& Danica Chen. Making data available is a huge positive direction for science, and makes my project of reproducing analysis of journal articles possible.\n\n# AI Use\n\nAll of the guidance given by generative AI for this article can be found in [this conversation](https://claude.ai/share/092e8d34-3cb6-429b-b4ee-7afe62a328e0). ",
    "supporting": [
      "WriteUp_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}