{
  "hash": "e73b41b15c6d1285c2e45eb64ef70e55",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab9\"\nauthor: \"Max Warriner\"\noutput: word_document\n---\n\nQ1.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lme4) # Load required libraries\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: Matrix\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(car) \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: carData\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:car':\n\n    recode\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(rcompanion)\nlibrary(FSA)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 methods overwritten by 'FSA':\n  method       from\n  confint.boot car \n  hist.boot    car \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n## FSA v0.9.6. See citation('FSA') if used in publication.\n## Run fishR() for related website and fishR('IFAR') for related book.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'FSA'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:car':\n\n    bootCase\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(emmeans)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'emmeans' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWelcome to emmeans.\nCaution: You lose important information if you filter this package's results.\nSee '? untidy'\n```\n\n\n:::\n\n```{.r .cell-code}\nstrength = c(40,36,42,36,44,37,41,42,40,42,34,40,50,49,52,50,36,33,34,36,25,31,27,27,70,72,67,70,56,62,55,59,48,50,48,48)\npgm = c(rep(\"I\",12),rep(\"II\",12),rep(\"III\",12))\ndose = c(rep(c(rep(\"High\",4),rep(\"Low\",4),rep(\"Placebo\",4) ),3))\ncamels = data.frame(pgm,dose,strength)\ncamels$pgm = as.factor(camels$pgm)\ncamels$dose = as.factor(camels$dose)\n```\n:::\n\n\na.\n\n1. Null: The training program of the camels does not affect their strength\nAlt: The training program of the camels does affect their strength\n\n2. Null: The Creatine dose of the camels does not affect their strength\nAlt: The creatine dose of the camels does affect their strength\n\n3. Null: The interaction between program and creatine does not affect their strength\nAlt: The interaction between program and creatine does affect their strength\n\n\nb. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(strength ~ interaction(pgm, dose), data = camels, \n        ylab = \"Strength\", xlab = \"program\", cex.lab = 1.2, cex.axis = 1.2)\n```\n\n::: {.cell-output-display}\n![](Biostatistics-Lab9-MaxWarriner_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Filter the 'rat' dataset to create groups based on 'sex' and 'fat'\nG1 = dplyr::filter(camels, pgm == \"I\" & dose == \"High\")$strength\nG2 = dplyr::filter(camels, pgm == \"II\" & dose == \"High\")$strength\nG3 = dplyr::filter(camels, pgm == \"III\" & dose == \"High\")$strength\nG4 = dplyr::filter(camels, pgm == \"I\" & dose == \"Low\")$strength\nG5 = dplyr::filter(camels, pgm == \"II\" & dose == \"Low\")$strength\nG6 = dplyr::filter(camels, pgm == \"III\" & dose == \"Low\")$strength\nG7 = dplyr::filter(camels, pgm == \"I\" & dose == \"Placebo\")$strength\nG8 = dplyr::filter(camels, pgm == \"II\" & dose == \"Placebo\")$strength\nG9 = dplyr::filter(camels, pgm == \"III\" & dose == \"Placebo\")$strength\n\n\ntestresult=scheirerRayHare(strength ~ pgm * dose, data = camels)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nDV:  strength \nObservations:  36 \nD:  0.9962677 \nMS total:  111 \n```\n\n\n:::\n\n```{.r .cell-code}\ntestresult\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Df  Sum Sq       H  p.value\npgm        2 2138.54 19.3383 0.000063\ndose       2  800.79  7.2414 0.026764\npgm:dose   4  727.54  6.5790 0.159881\nResiduals 27  203.63                 \n```\n\n\n:::\n:::\n\n\nInterpretation:\n\nAfter performing the Scheier-Ray hare Test, we observed that the distributions are similar so we can compare medians of the groups. After performing the test, we obtained significant results for the effect of program and dose on median strength, with p-values of 0.000063 and 0.026764 respectively. There was no significant interaction between the two. \n\nc. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ndunnTest(camels$strength, camels$dose, method=\"bh\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDunn (1964) Kruskal-Wallis multiple comparison\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n  p-values adjusted with the Benjamini-Hochberg method.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Comparison        Z     P.unadj     P.adj\n1     High - Low 1.446109 0.148146530 0.2222198\n2 High - Placebo 2.688405 0.007179434 0.0215383\n3  Low - Placebo 1.242295 0.214127632 0.2141276\n```\n\n\n:::\n\n```{.r .cell-code}\ndunnTest(camels$strength, camels$pgm, method=\"bh\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDunn (1964) Kruskal-Wallis multiple comparison\n  p-values adjusted with the Benjamini-Hochberg method.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Comparison          Z      P.unadj        P.adj\n1     I - II  0.4852716 6.274837e-01 0.6274836994\n2    I - III -3.5424827 3.963795e-04 0.0005945692\n3   II - III -4.0277543 5.631215e-05 0.0001689365\n```\n\n\n:::\n:::\n\n\nInterpretation:\n\nWe performed a follow up Dunn test on the effects of program and dose. When comparing dose level, we obtained significant results in the High-Placebo comparison (p-value = 0.0215383). When comparing program, we obtained significant results in the comparison between Programs 1 & 3 as well as 2 & 3, with p-values of 0.0005945692 and 0.0001689365 respectively. \n\nd. SUMMARY\n\nWe conducted a Scheier-Ray Hare test to determine if the dose level of creatine and the strength training program of camels affected their strength. After observing a similarity in distributions across all the 9 groups, we performed the test on the medians of the groups. After performing the test, we obtained significant results for the effect of dose level(p-value = 0.027) and program(p-value < 0.001) on the median of strength. The interaction was insignificant. A follow-up Dunn test was done and found a significant difference between the high and placebo doses for camels(p-value = 0.022) and between training programs 1&3(p-value < 0.001) and programs 2&3(p-value < 0.001). \n\n\nQ2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Data preperation and creating a dataframe\ncortex<-c(745,738,745,738,760,707,724,707,703,706,695,767,660,758,717,707,732,724,709,707)\nfood<-c(rep(\"Enriched\",7),rep(\"Commercial\",4),rep(\"Enriched\",3),rep(\"Commercial\",6))\nenvironment<-c(rep(\"Stimulating\",11),rep(\"Control\",9))\nrats<-data.frame(cortex, food, environment)\nstr(rats)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t20 obs. of  3 variables:\n $ cortex     : num  745 738 745 738 760 707 724 707 703 706 ...\n $ food       : chr  \"Enriched\" \"Enriched\" \"Enriched\" \"Enriched\" ...\n $ environment: chr  \"Stimulating\" \"Stimulating\" \"Stimulating\" \"Stimulating\" ...\n```\n\n\n:::\n:::\n\n\na.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy.anova1a = lm(cortex ~ food * environment, data = rats)\nmy.anova1b = lm(cortex ~ environment * food, data = rats)\n\nanova(my.anova1a) # PRINT ANOVA TABLE FOR THE FIRST MODEL\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: cortex\n                 Df Sum Sq Mean Sq F value  Pr(>F)  \nfood              1 2761.2 2761.25  4.7036 0.04551 *\nenvironment       1   44.8   44.81  0.0763 0.78587  \nfood:environment  1  524.0  524.05  0.8927 0.35880  \nResiduals        16 9392.8  587.05                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nanova(my.anova1b) # PRINT ANOVA TABLE FOR THE SECOND MODEL\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: cortex\n                 Df Sum Sq Mean Sq F value  Pr(>F)  \nenvironment       1   89.5   89.52  0.1525 0.70132  \nfood              1 2716.5 2716.54  4.6274 0.04709 *\nenvironment:food  1  524.0  524.05  0.8927 0.35880  \nResiduals        16 9392.8  587.05                  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\noptions(contrasts = c(unordered=\"contr.sum\", ordered=\"contr.poly\"))\nmy.anova1a = lm(cortex ~ food * environment, data = rats)\n# Perform Type III ANOVA and print the ANOVA table for the first model\nAnova(my.anova1a, type = 3) # For Type II: Anova(my.anova1a, type = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type III tests)\n\nResponse: cortex\n                  Sum Sq Df    F value Pr(>F)    \n(Intercept)      9314243  1 15866.1076 <2e-16 ***\nfood                2401  1     4.0894 0.0602 .  \nenvironment           27  1     0.0452 0.8343    \nfood:environment     524  1     0.8927 0.3588    \nResiduals           9393 16                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nb. Interpretation:\n\nIn both orders of doing type I SS, the food factor is significant (p-value < 0.05). However, when doing type III, no factor is significant. Because we have no specific reason for doing type I instead of type III, I would interpret this result as insignificant for all of the factors. \n\nQ3.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Data preparation\noffspring = c(18,20,15,27,30,20,28,30,17,29,35,30,32,28,35,25,30,19,30,25,28,29, 32,38,29,35,39,30,40,38,28,36,29,30,37,33,39,42,47,38,51,42,48,39,55)\ntemp = c(rep(\"70\",5), rep(\"75\",5), rep(\"80\",5),rep(\"70\",5), rep(\"75\",5), rep(\"80\",5),\nrep(\"70\",5), rep(\"75\",5), rep(\"80\",5))\nfeeding = c(rep(\"1 Feeding\",15), rep(\"2 Feedings\", 15), rep(\"3 Feedings\", 15))\n#Create the  dataframe and assign the factors.\nguppy = data.frame(offspring, temp, feeding)\nguppy$temp = as.factor(guppy$temp)\nguppy$feeding = as.factor(guppy$feeding)\nstr(guppy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t45 obs. of  3 variables:\n $ offspring: num  18 20 15 27 30 20 28 30 17 29 ...\n $ temp     : Factor w/ 3 levels \"70\",\"75\",\"80\": 1 1 1 1 1 2 2 2 2 2 ...\n $ feeding  : Factor w/ 3 levels \"1 Feeding\",\"2 Feedings\",..: 1 1 1 1 1 1 1 1 1 1 ...\n```\n\n\n:::\n:::\n\n\na.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(contrasts = c(unordered = \"contr.sum\", ordered = \"contr.poly\"))\nmy.anova = lmer(offspring ~ (1| temp) + (1 | feeding) + (1 | temp:feeding), data = guppy) # Fit the model\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nboundary (singular) fit: see help('isSingular')\n```\n\n\n:::\n\n```{.r .cell-code}\nresiduals = residuals(my.anova)\n\nhist(residuals, freq=FALSE, xlab=\"Residuals\", main=\"Residuals Histogram\")\ncurve(dnorm(x, mean(residuals), sd(residuals)), add=TRUE, col='red')\n```\n\n::: {.cell-output-display}\n![](Biostatistics-Lab9-MaxWarriner_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code}\nqqnorm(residuals); qqline(residuals)\n```\n\n::: {.cell-output-display}\n![](Biostatistics-Lab9-MaxWarriner_files/figure-html/unnamed-chunk-7-2.png){width=672}\n:::\n\n```{.r .cell-code}\nshapiro.test(residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals\nW = 0.97845, p-value = 0.5584\n```\n\n\n:::\n\n```{.r .cell-code}\nboxplot(offspring ~ interaction(feeding, temp), data = guppy, \n        ylab = \"Offspring\", xlab = \"Feeding & Temp\", cex.lab = 1.2, cex.axis = 1.2)\n```\n\n::: {.cell-output-display}\n![](Biostatistics-Lab9-MaxWarriner_files/figure-html/unnamed-chunk-7-3.png){width=672}\n:::\n:::\n\n\nInterpretation:\n\nOur analysis of the histrogram and qqplots show approximate normality. This is confirmed with a p-value of 0.5584 for the Shapiro normality test. When plotting the boxplots, we see an approximately similar distribution for each group, while we do have one outlier. \n\nb.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_no_temp = lmer(offspring ~ (1 | feeding) + (1 | feeding:temp), data = guppy, REML = FALSE)\nanova(model_no_temp, my.anova)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nrefitting model(s) with ML (instead of REML)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: guppy\nModels:\nmodel_no_temp: offspring ~ (1 | feeding) + (1 | feeding:temp)\nmy.anova: offspring ~ (1 | temp) + (1 | feeding) + (1 | temp:feeding)\n              npar    AIC    BIC  logLik deviance  Chisq Df Pr(>Chisq)   \nmodel_no_temp    4 301.12 308.35 -146.56   293.12                        \nmy.anova         5 295.82 304.85 -142.91   285.82 7.3055  1   0.006874 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel_no_feeding = lmer(offspring ~ (1 | temp) + (1 | feeding:temp), data = guppy, REML = FALSE)\nanova(model_no_feeding, my.anova)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nrefitting model(s) with ML (instead of REML)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: guppy\nModels:\nmodel_no_feeding: offspring ~ (1 | temp) + (1 | feeding:temp)\nmy.anova: offspring ~ (1 | temp) + (1 | feeding) + (1 | temp:feeding)\n                 npar    AIC    BIC  logLik deviance  Chisq Df Pr(>Chisq)   \nmodel_no_feeding    4 301.82 309.05 -146.91   293.82                        \nmy.anova            5 295.82 304.85 -142.91   285.82 8.0055  1   0.004664 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nmodel_no_interact = lmer(offspring ~ (1 | feeding) + (1 | temp), data = guppy, REML = FALSE)\nanova(model_no_interact, my.anova)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nrefitting model(s) with ML (instead of REML)\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nData: guppy\nModels:\nmodel_no_interact: offspring ~ (1 | feeding) + (1 | temp)\nmy.anova: offspring ~ (1 | temp) + (1 | feeding) + (1 | temp:feeding)\n                  npar    AIC    BIC  logLik deviance Chisq Df Pr(>Chisq)\nmodel_no_interact    4 293.82 301.05 -142.91   285.82                    \nmy.anova             5 295.82 304.85 -142.91   285.82     0  1     0.9999\n```\n\n\n:::\n:::\n\n\nInterpretation:\n1. Null: There is no significant variation in offspring due to water temperature in guppies\nAlternative: There is significant variation in offspring due to water temp. \n\n2. Null: There is no significant variation in offspring due to feeding frequency.\nAlternative: There is significant variation in offspring due to feeding frequency. \n\n3. Null: There is no significant variation in offspring due to the interaction between water temperature and feeding frequency.\nAlternative: There is significant variation in offspring due to the interaction between water temperature and feeding frequency.\n\nAfter performing the ANOVA test on all of the random factors, we obtain significant results for the effect of temperature and feeding frequency on variation with p-values of 0.006874a and 0.004664 respectively. The interaction was not significant.\n\nc.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_results = Anova(my.anova, type = \"III\") # Perform Type III ANOVA\nvariance_components = VarCorr(my.anova) # Extract variance components\nresidual_variance = attr(variance_components, \"sc\")^2 # Extract residual variance\n\n# Calculate the variance for random effects\ntemp_variance = attr(variance_components$temp, \"stddev\")^2\nfeeding_variance = attr(variance_components$feeding, \"stddev\")^2\ntemp_feeding_variance = attr(variance_components$`temp:feeding`, \"stddev\")^2\n# Calculate total variance (random effects and residual variance)\ntotal_variance = temp_variance + feeding_variance + temp_feeding_variance + residual_variance\n\n# Calculate percent variance contribution only if total variance is not zero\npercent_variance = c(\"temp (Random)\" = (temp_variance / total_variance) * 100,\n    \"feeding (Random)\" = (feeding_variance / total_variance) * 100,\n    \"temp:feeding (Random)\" = (temp_feeding_variance / total_variance) * 100,\n    \"Residuals\" = (residual_variance / total_variance) * 100)\npercent_variance\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        temp (Random).(Intercept)      feeding (Random).(Intercept) \n                         33.29509                          43.35845 \ntemp:feeding (Random).(Intercept)             Residuals.(Intercept) \n                          0.00000                          23.34646 \n```\n\n\n:::\n:::\n\n\nInterpretation:\n\nAfter performing a follow up variance calculation, we found that 33% of the variation can be attributed to the water temperature, 43% of the variation can be due to the feeding frequency, and 0% of the variation is due to the interaction between the two factors. \n\nd.\n\n\n::: {.cell}\n\n:::\n\n\nInterpretation:\n\n\ne. SUMMARY\n\nWe performed a model two, two-way ANOVA to test if the feeding frequency and the water temperature contributed significant variation in the offspring of guppies. The data passed the normality assumption by passing the shapiro test for normality. We had one outlier in the data but we continued on with the ANOVA test. After performing the test, we obtained significant effects on the variation due to water temperature and feeding frequency with p-values of 0.006874 and 0.004664 respectively. After performing a follow up test on the variation, we found that 33% of the variation is due to the water temperature and 43% of the variaion is due to the feeding frequency. \n\nQ4. \n\na.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1-pf(2.98,19,6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09040712\n```\n\n\n:::\n:::\n\n\nInterpretation:\nThe null hypothesis is that the elevation does not add significant variation to the biodiversity in soil invertebrates. They cannot reject the null hypothesis, because their p-value with a test statistic F(19&6-df) is 0.09, greater than 0.05.\n\nb.\n\n\n::: {.cell}\n\n:::\n\n\nInterpretation:\n\nExtra Practice 1.\n\na.\n\nb.\n\nc.\n\nd.\n\ne.\n\nf.\n\ng.",
    "supporting": [
      "Biostatistics-Lab9-MaxWarriner_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}