{
  "hash": "d6792179e9eaa08aaeab7da8394a487e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: HW1           # Title of the document\n\n# Bibliography Details\nbibliography: HW1References.bib  # Name of bib file in the same folder \nbibliographystyle: apa                   # Bibliography style\n\nexecute:\n  warning: false\n  message: false\n\n# Below will do html by default. To render the entire project\n# Use the following code:\n# quarto::quarto_render(\"HW1WriteUp.qmd\")\nformat:\n  html: \n    number-sections: TRUE\n    code-fold: TRUE\n    code-line-numbers: TRUE\n    cap-location: top \n  pdf:\n    documentclass: article\n    number-sections: TRUE\n    reference-section-title: \"References\" \n    code-fold: TRUE\n    code-line-numbers: TRUE\n    cap-location: top \n    include-in-header:\n      - text: |\n          \\usepackage{amsmath}\n          \\usepackage[dvipsnames]{xcolor}\n          \\usepackage[shortlabels]{enumitem}\n          \\usepackage{parskip}\n          \\usepackage{hyperref}\n          \\usepackage{geometry}\n          \\usepackage{float}\n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\nformat-links: [pdf]\n---\n\n\n \\normalsize\n\n\n::: {.cell}\n\n:::\n\n\n \\normalsize\n\n# Question 1\n@OSC15 attempted to replicate 100 psychology experiments from three journals:\n\n* Journal of Personality and Social Psychology (JPSP)\n* Journal of Experimental Psychology: Learning, Memory, and Cognition (JEP:\nLMC). \n* Psychological Science (PSCI)\n\n|Journal | Replicated | Not Replicated|\n|:--     |:--:         |:--:|  \n|JPSP    | 7          | 24|\n|JEP:LMC | 13         | 14|\n|PSCI    | 15         | 24|\n\nTheir work astonishingly showed that, empirically, only just over half of their attempts were successful. \n\n## Part a\nOverall, is there support for the claim that more than half of psychology research is able to be replicated?\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(stats)\nlibrary(pwr)\nlibrary(binom)\n\nreplicated = 7 + 13 + 25\nnot_replicated = 24 + 14 + 24\ntotal = replicated + not_replicated\n\nbinom.test(replicated, total, p = 0.5, alternative = \"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact binomial test\n\ndata:  replicated and total\nnumber of successes = 45, number of trials = 107, p-value = 0.9593\nalternative hypothesis: true probability of success is greater than 0.5\n95 percent confidence interval:\n 0.339836 1.000000\nsample estimates:\nprobability of success \n             0.4205607 \n```\n\n\n:::\n\n```{.r .cell-code}\nES.h(0.5, replicated/total)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1595546\n```\n\n\n:::\n\n```{.r .cell-code}\nbinom.exact(replicated, total)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  method  x   n      mean    lower     upper\n1  exact 45 107 0.4205607 0.325769 0.5198639\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nBased on an exact binomial test, there is not support for the claim that over half of psychology research is able to be replicated. We fail to reject our null hypothesis that $p = 0.5$ ($p$-value = 0.9593). A 95\\% confidence interval for our proportion is [0.33, 0.52]. Our effect size, cohen's h, is 0.160, indicating a small difference between our empirical proportion of 0.421 and our null proportion of 0.5. \n\n## Part b\nAssess whether the replication success rate varies across journals. \n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(effectsize)\n\nreplication_dat <- tibble(Replicated = c(7, 13, 15), \n                          Not_Replicated = c(24, 14, 24))\nrownames(replication_dat) <- c(\"JPSP\", \"JEP:LMC\", \"PSCI\")\n\nchisq.test(replication_dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  replication_dat\nX-squared = 4.2504, df = 2, p-value = 0.1194\n```\n\n\n:::\n\n```{.r .cell-code}\ncramers_v(replication_dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCramer's V (adj.) |       95% CI\n--------------------------------\n0.15              | [0.00, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n\n```{.r .cell-code}\ninterpret_cramers_v(0.15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"small\"\n(Rules: funder2019)\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nBased on the results from a Chi-Squared test of independence, there is no evidence for a statistically discernible difference in replication rates by journal ($\\chi^2 = 4.250$, $p = 0.119$). The effect size is small (Cramer's $v = 0.15$). \n\n# Question 2\nBelow, I simulate a rather quite annoying set of regression data.\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(0510)\nn <- 250\ndat <- tibble(x1 = rnorm(n, mean = 50, sd = 10),\n              x2 = factor(sample(c(\"A\", \"B\"), n, replace = TRUE)),\n              x3 = factor(sample(c(\"Control\", \"Treat\"), n, replace = TRUE)),\n              x4 = factor(sample(c(\"Low\", \"High\"), n, replace = TRUE)),\n              x5 = rnorm(n, mean = 0, sd = 1),\n              x6 = factor(sample(c(\"Group1\", \"Group2\"), n, replace = TRUE)),\n              x7 = rnorm(n, mean = 10, sd = 2),\n              x8 = rnorm(n, mean = 10, sd = 2)) |>\n        mutate(y = 5 +                          # Intercept\n                   # Quantitative x1\n                   2 * x1 +\n                   # Categorical x2\n                   (x2 == \"B\") * 10 +\n                   # Categorical x Categorical (x3*x4)\n                   (x3 == \"Treat\") * 5 + (x4 == \"High\") * 2 + \n                   (x3 == \"Treat\" & x4 == \"High\") * 15 +\n                   # Quantitative x Categorical  (x5*x6)\n                   3 * x5 + (x6 == \"Group2\") * 4 + \n                   (x5 * (x6 == \"Group2\")) * 8 + \n                   # Quantitative x Quantitative (x7*x8)\n                   1.5 * x7 + 0.5 * x8 + \n                   0.8 * (x7 * x8) + \n                   # Error\n                   rnorm(n, mean = 0, sd = 15))\n```\n:::\n\n\n \\normalsize\n\n## Part a\n\nFit the regression model.\n\n\\begin{align*}\n  Y_i =& \\beta_0  +\n       \\beta_1 x_{1i} + \\beta_2 I(x_{2i}=\\text{B})+ \\beta_3 I(x_{3i}=\\text{Treat}) + \\beta_4 (x_{4i}=\\text{High}) +\\\\\n       & \\beta_5 x_{5i} + \\beta_6 I(x_{6i}=\\text{Group 2}) + \\beta_7 x_{7i} + \\beta_8 x_{8i}+\\\\\n       & \\beta_9 (I(x_{3i}=\\text{Treat}) ~\\times~ I(x_{4i}=\\text{High})) + \\tag{Categorical $\\times$ Categorical}\\\\\n        & \\beta_{10} (x_{5i} ~\\times~ I(x_{6i}=\\text{Group 2})) +\\tag{Continuous $\\times$ Categorical}\\\\\n        & \\beta_{11} (x_{7i} ~\\times~ x_{8i}) +\n         \\epsilon_i \\tag{Continuous $\\times$ Continuous}\n\\end{align*}\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nformula = y ~ x1 + x2 + x3 * x4 + x5 * x6 + x7 * x8\n\nmod <- lm(formula, dat)\n```\n:::\n\n\n \\normalsize\n\n## Part b\nConduct a residual and outlier analysis.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(patchwork)\nsource(file = \"plotResiduals.R\")\n\nplotResiduals(mod)\n```\n\n::: {.cell-output-display}\n![](HW1WriteUp_files/figure-pdf/unnamed-chunk-6-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nA histogram of our linear model residuals shows that the residuals appear very normal and are centered around 0. The qq-plot of the residuals shows a very close fit between the Gaussian quantiles and sample quantiles. There are two residuals that are on the border of reasonability but that alone shouldn't be much concern. \n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsource(file = \"plotInfluence.R\")\nplotInfluence(mod)\n```\n\n::: {.cell-output-display}\n![](HW1WriteUp_files/figure-pdf/unnamed-chunk-7-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nThere is one observation with a high leverage, one point with a large negative DFFITs, and two observations with large positive or negative studentized residuals. Given that none of the observations have high Cook's D values, only one observation is flagged in two metrics, and the total sample size is large, these metrics on the influence of outliers appear fairly standard to a true linear model.\n\n## Part c\nInterpret the intercept, the coefficients on $x_1$ and $x_2$.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = formula, data = dat)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-42.979  -9.395  -1.054  10.150  42.305 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    12.41835   26.71681   0.465 0.642489    \nx1              2.13546    0.08944  23.876  < 2e-16 ***\nx2B            10.02851    1.79959   5.573 6.77e-08 ***\nx3Treat        21.70357    2.54065   8.543 1.59e-15 ***\nx4Low          -3.52182    2.53119  -1.391 0.165413    \nx5              2.48350    1.29418   1.919 0.056183 .  \nx6Group2        4.98495    1.80989   2.754 0.006336 ** \nx7              0.37174    2.61136   0.142 0.886920    \nx8             -0.92790    2.60484  -0.356 0.721990    \nx3Treat:x4Low -15.19194    3.66722  -4.143 4.77e-05 ***\nx5:x6Group2     6.94743    1.85460   3.746 0.000225 ***\nx7:x8           0.92871    0.25937   3.581 0.000415 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 14.03 on 238 degrees of freedom\nMultiple R-squared:  0.8562,\tAdjusted R-squared:  0.8495 \nF-statistic: 128.8 on 11 and 238 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nThe intercept tells us that for a point with all numeric variables ($x_1$, $x_5$, $x_7$, $x_8$) equalling 0, $x_2 =$ \"A\", $x_3=$ \"Control\", $x_4 =$ \"High\", and $x_6 =$ \"Group 1\", the model would predict a $y$ value of 12.418. \n\nThe $x_1$ coefficient tells us that for every unit increase in $x_1$, we'd expect a $y$ value increase of 2.135. \n\nThe $x_2$ coefficient tells us that being in the \"B\" group is associated with a 10.029 increase in $y$ compared to the \"A\" group. \n\n## Part d\nUntangle and interpret the $x_3*x_4$ interaction.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggthemes)\nlibrary(emmeans)\nmod.emm <- summary(emmeans(mod, ~ x4 | x3))\nmod.emm$x4 = factor(mod.emm$x4, levels = c(\"Low\", \"High\"))\n\nggplot(data = mod.emm, aes(x = x3, y = emmean, color = x4)) + \n  geom_point(position = position_dodge(width = 0.5))+ \n  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.15, position = position_dodge(width = 0.5)) + \n  xlab(bquote(x[3])) + \n  labs(color = bquote(x[4])) + \n  ylab(\"Estimated Marginal Mean\") + \n  theme_clean()\n```\n\n::: {.cell-output-display}\n![](HW1WriteUp_files/figure-pdf/unnamed-chunk-9-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod.pairs <- emmeans(mod, ~ x4 | x3)\npairs(mod.pairs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nx3 = Control:\n contrast   estimate   SE  df t.ratio p.value\n High - Low     3.52 2.53 238   1.391  0.1654\n\nx3 = Treat:\n contrast   estimate   SE  df t.ratio p.value\n High - Low    18.71 2.60 238   7.195  <.0001\n\nResults are averaged over the levels of: x2, x6 \n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nIf we view the effect of $x_4$ across the levels of $x_3$, we see that in the control group, having $x_4=$ \"High\" was associated with a 3.52 greater value in $y$ as compared to $x_4$ \"Low\", a difference not statistically discernible ($p = 0.165$). In the treat group, having $x_4$ = \"High\" was associated with 18.71 greater value in  $y$ as compared to $x_4=$ \"Low\", a statistically discernible difference ($p < 0.0001$). \n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = mod.emm, aes(x = x4, y = emmean, color = x3)) + \n  geom_point(position = position_dodge(width = 0.5))+ \n  geom_errorbar(aes(ymin = lower.CL, ymax = upper.CL), width = 0.15, position = position_dodge(width = 0.5)) + \n  xlab(bquote(x[4])) + \n  labs(color = bquote(x[3])) + \n  ylab(\"Estimated Marginal Mean\") + \n  theme_clean()\n```\n\n::: {.cell-output-display}\n![](HW1WriteUp_files/figure-pdf/unnamed-chunk-11-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod.pairs <- emmeans(mod, ~ x3 | x4)\npairs(mod.pairs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nx4 = High:\n contrast        estimate   SE  df t.ratio p.value\n Control - Treat   -21.70 2.54 238  -8.543  <.0001\n\nx4 = Low:\n contrast        estimate   SE  df t.ratio p.value\n Control - Treat    -6.51 2.66 238  -2.445  0.0152\n\nResults are averaged over the levels of: x2, x6 \n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nIf we view the effect of $x_3$ across the levels of $x_4$, we see that in the low group, having $x_3$ = \"Treat\" was associated with 6.51 greater value in  $y$ as compared to $x_3=$ \"Control\", a statistically discernible difference ($p = 0.015$). In the high group, having $x_3$= \"Treat\" was associated with a 21.70 greater value in $y$ as compared to $x_3=$ \"Control\", a statistically discernible difference ($p <0.0001$).\n\n\n\n## Part e\nUntangle and interpret the $x_5*x_6$ interaction.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmip(mod, x6 ~ x5, \n      at = list(x5 = seq(min(dat$x5), max(dat$x5), length.out = 100)), \n      CIs = TRUE) +\n  ylab(\"Estimated Marginal Mean\") +\n  xlab(bquote(x[5])) +\n  labs(color = bquote(x[6])) + \n  theme_clean()\n```\n\n::: {.cell-output-display}\n![](HW1WriteUp_files/figure-pdf/unnamed-chunk-13-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nFrom the interaction plot we see that the slope of $x_5$ appears to be greater for the Group 2 in $x_6$ than Group 1. \n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemtrends(mod, \"x6\", var = \"x5\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n x6     x5.trend   SE  df lower.CL upper.CL\n Group1     2.48 1.29 238   -0.066     5.03\n Group2     9.43 1.34 238    6.798    12.06\n\nResults are averaged over the levels of: x2, x3, x4 \nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nThe trend of $x_5$ in Group 1 is 2.48 (95\\% CI: [-0.066, 5.03]), while the trend of $x_5$ in Group 2 is 9.43 (95\\% CI: [6.798, 12.06]). \n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(emtrends(mod, \"x6\", var = \"x5\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast        estimate   SE  df t.ratio p.value\n Group1 - Group2    -6.95 1.85 238  -3.746  0.0002\n\nResults are averaged over the levels of: x2, x3, x4 \n```\n\n\n:::\n:::\n\n\n \\normalsize\n\n\nThe trend of $x_5$ for Group 2 is 6.95 greater than the trend for Group 1, a difference that is statistically discernible ($p=0.0002$). \n\n\n\n## Part f\nUntangle and interpret the $x_7*x_8$ interaction.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx7.vals <- c(\n  low  = mean(dat$x7) - sd(dat$x7),\n  mean = mean(dat$x7),\n  high = mean(dat$x7) + sd(dat$x7)\n)\n\nemmip(mod, x7 ~ x8, \n      at = list(\n        x8 = seq(min(dat$x8), max(dat$x8), length.out = 100),\n        x7 = round(x7.vals, 2)\n      ),\n      CIs = TRUE) +\n  xlab(bquote(x[8])) +\n  ylab(\"Estimated Marginal Mean\") +\n  labs(color = bquote(x[7]), fill = bquote(x[7])) +\n  theme_clean()\n```\n\n::: {.cell-output-display}\n![](HW1WriteUp_files/figure-pdf/unnamed-chunk-16-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nmod.emt <- emtrends(mod, ~ x7, var = \"x8\", at = list(x7 = round(x7.vals,2)))\n\npairs(mod.emt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast          estimate    SE  df t.ratio p.value\n x78.38 - x710.22     -1.71 0.477 238  -3.581  0.0012\n x78.38 - x712.06     -3.42 0.954 238  -3.581  0.0012\n x710.22 - x712.06    -1.71 0.477 238  -3.581  0.0012\n\nResults are averaged over the levels of: x2, x3, x4, x6 \nP value adjustment: tukey method for comparing a family of 3 estimates \n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nTrends for $x_8$ are discernibly different at low, average, and high (+/-1 SD) levels of $x_7$, increasing by 1.71 at each level (all $p$-values = 0.0012). \n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(interactions)\n\njohnson_neyman(mod, pred = x8, modx = x7)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nJOHNSON-NEYMAN INTERVAL\n\nWhen x7 is OUTSIDE the interval [-9.96, 4.25], the slope of x8 is p < .05.\n\nNote: The range of observed values of x7 is [4.89, 14.60]\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](HW1WriteUp_files/figure-pdf/unnamed-chunk-17-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nA Johnson-Neyman plot shows us that the slope of $x_8$ increases as $x_7$ increases and is statistically discernible ($p<0.05$) for the range of observed data. For theoretical lower levels of $x_7$ (<4.25), the slope of $x_8$ would not be statistically discernible ($p\\geq 0.05$).\n\n## Part g\nStandardize the continuous data and refit the regression model. What do you notice about the coefficient estimates in relation to your answers to parts d-f?\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_scaled <- dat |>\n  mutate(x1 = scale(x1), \n         x5 = scale(x5), \n         x7 = scale(x7), \n         x8 = scale(x8), \n         y = scale(y))\n\nmod_scaled <- lm(formula, dat_scaled)\nsummary(mod_scaled)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = formula, data = dat_scaled)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.18783 -0.25965 -0.02912  0.28052  1.16921 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   -0.35574    0.06272  -5.672 4.08e-08 ***\nx1             0.60221    0.02522  23.876  < 2e-16 ***\nx2B            0.27716    0.04974   5.573 6.77e-08 ***\nx3Treat        0.59983    0.07022   8.543 1.59e-15 ***\nx4Low         -0.09733    0.06996  -1.391 0.165413    \nx5             0.06803    0.03545   1.919 0.056183 .  \nx6Group2       0.12472    0.04985   2.502 0.013019 *  \nx7             0.49350    0.02548  19.369  < 2e-16 ***\nx8             0.45617    0.02527  18.052  < 2e-16 ***\nx3Treat:x4Low -0.41987    0.10135  -4.143 4.77e-05 ***\nx5:x6Group2    0.19030    0.05080   3.746 0.000225 ***\nx7:x8          0.09094    0.02540   3.581 0.000415 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.3879 on 238 degrees of freedom\nMultiple R-squared:  0.8562,\tAdjusted R-squared:  0.8495 \nF-statistic: 128.8 on 11 and 238 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nMost of the $p$-values for the coefficients have stayed the same, but some, such as $x_6$, $x_7$, and $x_8$, have changed. I'm not entirely sure why this. \n\n# Question 3\nBelow, I simulated data that have a non-linear relationship.\n\n \\scriptsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7272)\nn <- 250\ndat <- tibble(x = rnorm(n, mean = 1, sd = 0.2)) |>\n  mutate(y = exp(2.9 + 1.8*x + rnorm(n, mean = 0, sd = 1)))\n```\n:::\n\n\n \\normalsize\n\n## Part a\nFit the model $y_i = \\beta_0 + \\beta_1 x_{1i} + \\epsilon_i$ and interpret the coefficient on $x$.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp_mod <- lm(y ~ x, data = dat)\nsummary(exp_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = y ~ x, data = dat)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-209.57 -109.57  -46.30   39.57 1750.50 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)   \n(Intercept)   -26.45      66.85  -0.396  0.69269   \nx             190.28      65.99   2.883  0.00428 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 209.6 on 248 degrees of freedom\nMultiple R-squared:  0.03243,\tAdjusted R-squared:  0.02853 \nF-statistic: 8.313 on 1 and 248 DF,  p-value: 0.004281\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nFrom an OLS model, we expect that for every unit increase in $x$, $y$ would increase by 190.28. \n\n## Part b\nConduct a residual analysis on the model in part a to demonstrate how to identify when you need a log transformation.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotResiduals(exp_mod)\n```\n\n::: {.cell-output-display}\n![](HW1WriteUp_files/figure-pdf/unnamed-chunk-21-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nThe residual analysis gives us several clues as to why a log transform would be helpful in this situation: mainly, the residuals are heavily right skewed with a huge tail, and all of the large residuals are positive. Also, the qq-plot shows a predictable deviance from the standard gaussian quantiles at high sample quantiles. \n\n## Part c\nFit the model $\\log(y_i) = \\beta_0 + \\beta_1 x_{1i} + \\epsilon_i$ and interpret the coefficient on $x$.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog_mod <- lm(log(y) ~ x, data = dat)\nsummary(log_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log(y) ~ x, data = dat)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.35217 -0.61174  0.05022  0.67488  2.94090 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   3.5528     0.3046  11.664  < 2e-16 ***\nx             1.0654     0.3007   3.543 0.000472 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9552 on 248 degrees of freedom\nMultiple R-squared:  0.04818,\tAdjusted R-squared:  0.04434 \nF-statistic: 12.55 on 1 and 248 DF,  p-value: 0.0004723\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nBased on this log transformed model, for every unit increase in $x$, we'd expect a 1.0654 increase in log($y$).\n\n## Part d\nConduct a residual analysis on the model in part c to demonstrate that the conditions for using regression are met.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotResiduals(log_mod)\n```\n\n::: {.cell-output-display}\n![](HW1WriteUp_files/figure-pdf/unnamed-chunk-23-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\nThe log transformed model fits the Gaussian distribution much better now,the histogram is centered around 0, and it fits the qqplot almost perfectly. There's only residual that's slightly large enough to be noticeable among the rest of the residuals, but that's likely to happen with a sample size of 250.\n\n## Part e\nStandardize $x$ and fit the model $\\log(y_i) = \\beta_0 + \\beta_1 z_{1i} + \\epsilon_i$ and interpret the coefficient on $z$.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nscaled_dat <- dat |>\n  mutate(x = scale(x))\n\nsummary(lm(log(y) ~ x, data = dat))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log(y) ~ x, data = dat)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.35217 -0.61174  0.05022  0.67488  2.94090 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   3.5528     0.3046  11.664  < 2e-16 ***\nx             1.0654     0.3007   3.543 0.000472 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9552 on 248 degrees of freedom\nMultiple R-squared:  0.04818,\tAdjusted R-squared:  0.04434 \nF-statistic: 12.55 on 1 and 248 DF,  p-value: 0.0004723\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nThe standardized and log transformed model shows us that for a standard deviation increase in $x$, we'd expect a 1.0654 increase in log($y$).\n\n# AI Disclosure\n\nI used Claude AI throughout to help write code and generally to remember how to use EMM packages and functions. The conversation of everything used can be found [here](https://claude.ai/share/e890f8b7-0bd0-4d90-8498-1f0ec5ab5bf5). \n",
    "supporting": [
      "HW1WriteUp_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}