---
title: "Data Analysis II: Overview"
format: html
resources:
  - project.pdf
---

I'm currently taking this class in the Fall of 2026 as an independent study with Prof. William Cipolli

This is the description of the course from the Colgate catalog:

"An applied regression course that involves modeling and interpreting data with statistical learning methods in regression and classification. Topics include K Nearest Neighbors, Logistic Regression, Discriminant Analysis, Ridge Regression, LASSO, Regression Splines, Generalized Additive Models, Tree-Based Models, and Support Vector Machines, with the choice of additional topics determined by the instructor (e.g., Bootstrapping, Principal Components Analysis, Latent Profile Analysis, Clustering, structural equation models). While applied, it aims to combine theory and application to emphasize the need for understanding each method’s theoretical foundation. This conversation is had through illustrating a variety of inferences, residual analyses and fully exploring the implications of our assumptions."

In my case, I will be primarily working on a statistical portfolio as found in Option 1 of this document: 

{{< pdf project.pdf width=100% height=600 >}}

The premise of the portfolio is to take these specific topics:

- Mixed Effects Regression
- Poisson Regression (usual and mixed effects)
- Negative Binomial (usual and mixed effects)
- Zero-Inflated Models
- Logistic Regression (usual and mixed effects)
- Multinomial Regression
- Neural Networks
- Random Forests

and find recently published journal articles, with data available, that use these topics and I try to reproduce the goals of their statistical analysis as best I can to see if I come up with the same results and interpretations as the authors. 

Also available is the traditional homeworks from the class that I'll use to learn about the topics before applying them. 


